spring.application.name=Institute-Management-System
server.port=8081

# PostgreSQL DB Configuration
spring.datasource.url=jdbc:postgresql://dpg-d1ol58c9c44c73fp6pj0-a.region.render.com:5432/institute_oxe9
spring.datasource.username=institute_oxe9_user
spring.datasource.password=Adveh1MJtJ14UCU5XLa5foVGRE4qFq45
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
